destType: Amazon_S3
destBucket: test-fs-app
destPrefix: testdth/102101/
destRegion: ap-northeast-2
destEndpoint:
destCredential: global
destInCurrentAccount: false
skipCompare: true

srcType: Aliyun_OSS
srcBucket: test-fs-app
srcPrefix: 702/
srcRegion:
srcEndpoint: oss-cn-beijing.aliyuncs.com
srcCredential: cn-oss
srcStorageClass: STANDARD
srcInCurrentAccount: false

jobTableName: test-table
jobQueueName: test-queue

options:
  chunkSize: 10
  multipartThreshold: 10
  maxKeys: 1000
  messageBatchSize: 10
  finderDepth: 0
  finderNumber: 8
  workerNumber: 8
  includeMetadata: false