srcType: Amazon_S3
srcBucket: test-fs-app
srcPrefix: 509
srcRegion: ap-northeast-2
srcEndpoint:
srcCredential: global
srcInCurrentAccount: false
skipCompare: false

destType: Aliyun_OSS
destBucket: fs-app
destPrefix: testdth/1005/
destRegion:
destEndpoint: oss-cn-beijing.aliyuncs.com
destCredential: cn-oss
destStorageClass: STANDARD
destInCurrentAccount: false
destAcl: bucket-owner-full-control

jobTableName: test-table
jobQueueName: test-queue

options:
  chunkSize: 10
  multipartThreshold: 10
  maxKeys: 1000
  messageBatchSize: 10
  finderDepth: 0
  finderNumber: 8
  workerNumber: 8
  includeMetadata: false