destType: Amazon_S3
destBucket: fs-app-kr
destPrefix: testdth/1004/
destRegion: ap-northeast-2
destEndpoint:
destCredential: global
destInCurrentAccount: false
skipCompare: false

srcType: Aliyun_OSS
srcBucket: fs-app
srcPrefix: testdth
srcRegion:
srcEndpoint: oss-cn-beijing.aliyuncs.com
srcCredential: cn-oss
srcStorageClass: STANDARD
srcInCurrentAccount: false
srcAcl: bucket-owner-full-control

jobTableName: test-table
jobQueueName: test-queue

options:
  chunkSize: 10
  multipartThreshold: 10
  maxKeys: 1000
  messageBatchSize: 10
  finderDepth: 0
  finderNumber: 8
  workerNumber: 8
  includeMetadata: false